POST https://gedearya.sipintek.com/api/message-list HTTP/1.1
X-Requested-With: XMLHttpRequest
content-type: application/json 

{
    "email": "aryaxxx487@gmail.com",
    "name": "arya gede",
    "email_to": "igedearya359@gmail.com", 
    "subject": "testing",
    "message": "testing bro ku"
}

# Authorization: Bearer 6|X8mBP8t2GCs85u6N3bIduQUDVI7WuD9GHWVv4ZKk
###
GET https://gedearya.sipintek.com/api/message-list HTTP/1.1
Authorization: Bearer 8|T9sUwzcxmzubLqj6nfH3o16YS6CIr9JHJWbcGMjp
X-Requested-With: XMLHttpRequest

###
GET https://gedearya.sipintek.com/api/message-list/5 HTTP/1.1
X-Requested-With: XMLHttpRequest

###
PUT https://gedearya.sipintek.com/api/message-list/5 HTTP/1.1
X-Requested-With: XMLHttpRequest
content-type: application/json

{
    "name": "Test 1 2 3",
    "email_to": "totest2@gmail.com",
    "subject": "untuk makan baju baru lagi lo",
    "message": "nande-nade tabai maji deyo yo"
}

###
DELETE https://gedearya.sipintek.com/api/message-list/5 HTTP/1.1
X-Requested-With: XMLHttpRequest

###
