POST https://gedearya.sipintek.com/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "123456"
}

###
POST https://gedearya.sipintek.com/api/pages HTTP/1.1
X-Requested-With: XMLHttpRequest
Authorization: Bearer 5|07gNuKSvAVbJZoI5FAibVQf7gjoueeEy829NyhxJ
content-type: application/json

{
    "title":"Page 1",
    "type":"page",
    "meta_keyword":"kk",
    "meta_decryption":"dd",
    "publish":false,
    "publish_time":"2022-04-01 05:58:00",
    "show_comment":true,
    "url":"page1"
}

###
GET https://gedearya.sipintek.com/api/pages HTTP/1.1
X-Requested-With: XMLHttpRequest
Authorization: Bearer 5|07gNuKSvAVbJZoI5FAibVQf7gjoueeEy829NyhxJ


###
GET https://gedearya.sipintek.com/api/pages/85bd0806-e56b-4bc8-80ec-5461b895e6d1 HTTP/1.1
X-Requested-With: XMLHttpRequest
Authorization: Bearer 7|ccbunOmcXEIcqojGH69UElJov5lJ7DA31vYrxTkA

###
PUT https://gedearya.sipintek.com/api/pages/a9501e34-8bf7-411c-ba5e-0c90356861f4 HTTP/1.1
X-Requested-With: XMLHttpRequest
Authorization: Bearer 5|07gNuKSvAVbJZoI5FAibVQf7gjoueeEy829NyhxJ
content-type: application/json

{
    "title": "Post 1",
    "type": "post",
    "meta_keyword": "kk",
    "meta_decryption": "dd",
    "publish": "1",
    "publish_time": "2022-04-01 05:45:00",
    "show_comment": "0",
    "url": "post4"
}

###
DELETE https://gedearya.sipintek.com/api/pages/a9501e34-8bf7-411c-ba5e-0c90356861f4 HTTP/1.1
X-Requested-With: XMLHttpRequest
Authorization: Bearer 5|07gNuKSvAVbJZoI5FAibVQf7gjoueeEy829NyhxJ
